### ISSUE TITLE
Failed to detect a provider for FreeBSD 10.2

### ISSUE THREAD

**Issue by legal90** [poise/poise-service#36]
Hi! In the consul cookbook we have a "poise_service" resource failure on FreeBSD due to `ProviderNotFound` exception. Is it supported in "poise_service" ? Is there a way to work it around?
```
         * consul_service[consul] action enable
           * directory[/var/lib/consul] action create (up to date)
           * poise_service[consul] action enable

             ================================================================================
             Error executing action `enable` on resource 'poise_service[consul]'
             ================================================================================

             Chef::Exceptions::ProviderNotFound
             ----------------------------------
             Cannot find a provider for poise_service[consul] on freebsd version 10.2-RELEASE-p7

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:89:in `block in action_enable'
             /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:154:in `notify_if_service'
             /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:88:in `action_enable'
             /tmp/kitchen/cache/cookbooks/consul/libraries/consul_service.rb:80:in `action_enable'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/consul/recipes/default.rb

       53: consul_service service_name do |r|
       54:   version node['consul']['version']
       55:   config_file config.path
       56:   program install.consul_program
       57:
       58:   unless windows?
       59:     user node['consul']['service_user']
       60:     group node['consul']['service_group']
       61:   end
       62:   if node['consul']['service']

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/consul/recipes/default.rb:53:in `from_file'

             poise_service("consul") do
        action [:enable]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        service_name "consul"
        command "/opt/consul/0.7.1/consul agent -config-file=/etc/consul/consul.json -config-dir=/etc/consul/conf.d"
        directory "/var/lib/consul"
        user "consul"
        environment {"GOMAXPROCS"=>"2", "PATH"=>"/usr/local/bin:/usr/bin:/bin"}
        options_systemd {"template"=>"consul:systemd.service.erb"}
        options_sysvinit {"template"=>"consul:sysvinit.service.erb"}
        options_upstart {"template"=>"consul:upstart.service.erb", "executable"=>"/opt/consul/0.7.1/consul"}
             end

             Platform:
             ---------
             x86_64-freebsd10.2
```

Thanks!

**Comment by coderanger** [comment]
I don't have a provider for FreeBSD but the design is such that you could write one in your own cookbook. If it's simple enough to not need any external dependencies I would be happy to include it in poise-service, but I'm going to close that as I don't plan to write one myself due to a lack of knowledge of BSD internals. Check out things like `poise-service-runit` and `poise-monit` for examples of writing providers as plugins.
