### ISSUE TITLE
How do I write ChefSpec for my `poise_X` resources?

### ISSUE THREAD

**Issue by maraaaa** [poise/poise-service#40]
Hello,

How do I write ChefSpec tests for my poise-service resources?  I've included `depends 'poise-service'` in my metadata.rb.

I attempted to write two tests:

```
[maraaaa@chef foo_myapp]$ rspec spec/unit/recipes/ruby_app_spec.rb

foo_myapp::ruby_app
  When all attributes are default, on an unspecified platform
    converges successfully
    creates socket directory (FAILED - 1)
    creates service account (FAILED - 2)
    creates startup script (FAILED - 3)

Failures:

  1) foo_myapp::ruby_app When all attributes are default, on an unspecified platform creates socket directory
     Failure/Error:
       expect(chef_run).to create_directory('/run/myapp')
         .with(
           user: 'foo',
           group: 'nginx',
           mode: '2755'
         )

       expected "directory[/run/myapp]" with action :create to be in Chef run. Other directory resources:



     # ./spec/unit/recipes/ruby_app_spec.rb:21:in `block (3 levels) in <top (required)>'

  2) foo_myapp::ruby_app When all attributes are default, on an unspecified platform creates service account
     Failure/Error:
       expect(chef_run).to poise_service_user('foo')
         .with(
           home: 'foo'
         )

     NoMethodError:
       undefined method `poise_service_user' for #<RSpec::ExampleGroups::fooSpaceDeviceRubyApp::WhenAllAttributesAreDefaultOnAnUnspecifiedPlatform:0x00000003675220>
     # ./spec/unit/recipes/ruby_app_spec.rb:30:in `block (3 levels) in <top (required)>'

  3) foo_myapp::ruby_app When all attributes are default, on an unspecified platform creates startup script
     Failure/Error:
       expect(chef_run).to poise_service('myapp')
         .with(
           command: 'RACK_ENV=production bundle exec unicorn -l unix:/run/myapp/myapp.socket'
         )

     NoMethodError:
       undefined method `poise_service' for #<RSpec::ExampleGroups::fooSpaceDeviceRubyApp::WhenAllAttributesAreDefaultOnAnUnspecifiedPlatform:0x007f4cb021a2d8>
       Did you mean?  disable_service
     # ./spec/unit/recipes/ruby_app_spec.rb:37:in `block (3 levels) in <top (required)>'

Finished in 4.06 seconds (files took 3.06 seconds to load)
4 examples, 3 failures

Failed examples:

rspec ./spec/unit/recipes/ruby_app_spec.rb:20 # foo_myapp::ruby_app When all attributes are default, on an unspecified platform creates socket directory
rspec ./spec/unit/recipes/ruby_app_spec.rb:29 # foo_myapp::ruby_app When all attributes are default, on an unspecified platform creates service account
rspec ./spec/unit/recipes/ruby_app_spec.rb:36 # foo_myapp::ruby_app When all attributes are default, on an unspecified platform creates startup script

```

Now, notably, I'm writing my tests before I've written any cookbook code, so yea, I expect my "createss socket directory" resource test to fail.  However, the:

```
NoMethodError:
       undefined method `poise_service' for #
```

Means, that I'm not doing something right in my tests to declare a `poise_service` resource.

haha... I was totally trying to copy my cookbook code, but I literally haven't written any recipes because I'm determined to do the TDD thing! :)

Most custom libraries include a "matchers" lib that has the matchers that do the testing.  But you're using your `halite` (I live the name BTW) gem to build the cookbook, so I have no idea where I'd look for "custom matchers".

If you give me an example, I'd be happy to wite the wiki page/documentation.  :)

Thanks,
- @maraaaa

**Comment by maraaaa** [comment]
This seems to work:

```
expect(chef_run).to create_poise_service_user('foo').with(home: '/foo')

expect(chef_run).to enable_poise_service('bar').with(command: command: 'bundle exec unicorn -p 8080')
```
